---
# - name: Get VM "{{ vm_name }}" folder path
#   vmware_guest_find:
#     hostname: "{{ vcenter_server }}"
#     username: "{{ vcenter_user }}"
#     password: "{{ vcenter_pass }}"
#     validate_certs: False
#     name: "{{ vm_name }}"
#   delegate_to: localhost
#   register: vm_folder
#   tags: folder

# - name: Print VM "{{ vm_name }}" folder path
#   debug:
#     msg: "{{ vm_folder.folders }}"

# - name: Get VM "{{ vm_name }}" uuid
#   vmware_vm_info:
#     hostname: "{{ vcenter_server }}"
#     username: "{{ vcenter_user }}"
#     password: "{{ vcenter_pass }}"
#     validate_certs: "{{ validate_certs }}"
#     # datacenter: "{{ datacenter }}"
#     folder: "{{ vm_folder.folders | first}}"
#     # name: "{{ vm_name }}"
#   register: vm_facts
# #   tags: uuid

# - name: Print VM "{{ vm_name }}" UUID
#   debug:
#     msg: "{{ vm_facts }}"

# - name: Restart VM "{{ vm_name }}"
#   vmware_guest:
#     hostname: "{{ vcenter_server }}"
#     username: "{{ vcenter_user }}"
#     password: "{{ vcenter_pass }}"
#     validate_certs: "{{ validate_certs }}"
#     # datacenter: "{{ datacenter }}"
#     # uuid: "{{ vm_facts }}"
#     name: "{{ vm_name }}"
#     state: poweredoff
#   delegate_to: localhost
# #   tags: restart

- name: Restart "{{ vm_name }}" 
  vmware_guest_powerstate:
    hostname: "{{ vcenter_server }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pass }}"
    validate_certs: "{{ validate_certs }}"
    name: "{{ vm_name }}"
    state: restarted
    state_change_timeout: 200
  delegate_to: localhost
  register: restarted_vm

- name: Print VM "{{ vm_name }}" restart status
  debug:
    msg: "{{ restarted_vm }}"
  
