---
- name: Get VM "{{ vm_name }}" folder path
  vmware_guest_find:
    hostname: "{{ vcenter_server }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pass }}"
    validate_certs: False
    name: "{{ vm_name }}"
  delegate_to: localhost
  register: vm_folder
  tags: folder

- name: Print VM "{{ vm_name }}" folder path
  debug:
    msg: "{{ vm_folder .folders}}"

# - name: Get VM "{{ vm_name }}" uuid
#   vmware_guest_info:
#     hostname: "{{ vcenter_server }}"
#     username: "{{ vcenter_user }}"
#     password: "{{ vcenter_pass }}"
#     validate_certs: "{{ validate_certs }}"
#     datacenter: "{{ datacenter }}"
#     folder: "/{{datacenter}}/vm"
#     name: "{{ vm_name }}"
#   register: vm_facts
#   tags: uuid

# - name: Restart VM "{{ vm_name }}"
#   vmware_guest:
#     hostname: "{{ vcenter_server }}"
#     username: "{{ vcenter_user }}"
#     password: "{{ vcenter_pass }}"
#     validate_certs: "{{ validate_certs }}"
#     datacenter: "{{ datacenter }}"
#     uuid: "{{ vm_facts }}"
#     state: poweredoff
#   delegate_to: localhost
#   tags: restart
